In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [3]:
plt.rcParams["figure.figsize"] = [8, 6]

In [4]:
train_set = pd.read_csv('train.csv')
test_set = pd.read_csv('test.csv')
print 'train_set shape: '
print train_set.shape
print 'test_set shape: ' 
print test_set.shape

train_set shape:
(113845, 2)
test_set shape:
(113845, 2)

In [5]:
train_set['Sequence'] = train_set['Sequence'].apply(lambda x: x.split(','))
train_set['length'] = pd.Series(list(train_set['Sequence'].apply(lambda x: len(x))), index=train_set.index)
train_set['flag'] = 'train'
test_set['Sequence'] = test_set['Sequence'].apply(lambda x: x.split(','))
test_set['length'] = pd.Series(list(test_set['Sequence'].apply(lambda x: len(x))), index=test_set.index)
test_set['flag'] = 'test'
df = pd.concat([train_set, test_set])
df = df.sort_values('Id')

In [6]:
df[:50]

    Id                                           Sequence  length   flag
0    1  [1, 0, 0, 2, 24, 552, 21280, 103760, 70299264,...      11   test
1    2  [1, 1, 5, 11, 35, 93, 269, 747, 2115, 5933, 16...      27   test
0    3  [1, 3, 13, 87, 1053, 28576, 2141733, 508147108...      14  train
2    4  [0, 1, 101, 2, 15, 102, 73, 3, 40, 16, 47, 103...      51   test
3    5  [1, 4, 14, 23, 42, 33, 35, 34, 63, 66, 87, 116...      50   test
4    6  [1, 1, 2, 5, 4, 2, 6, 13, 11, 4, 10, 10, 12, 6...      70   test
1    7  [1, 2, 1, 5, 5, 1, 11, 16, 7, 1, 23, 44, 30, 9...      57  train
2    8  [1, 2, 4, 5, 8, 10, 16, 20, 32, 40, 64, 80, 12...      41  train
5    9  [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, ...      48   test
6   10  [1, 1, 2, 5, 13, 36, 111, 347, 1134, 3832, 131...      30   test
3   11  [1, 8, 25, 83, 274, 2275, 132224, 1060067, 331...      20  train
7   12  [0, 0, 0, 0, 112, 40286, 5485032, 534844548, 4...      15   test
4   13  [1, 111, 12211, 1343211, 147753211, 1625285321...      12  train
8   14  [4, 41, 358, 3136, 52618, 2219896, 180648122, ...      13   test
5   15  [1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 5, ...      73  train
6   16  [840, 1320, 1680, 2520, 3192, 3432, 4920, 5208...      36  train
9   17  [1, 0, 2, 12, 216, 5280, 190800, 9344160, 5980...      15   test
7   18  [1, 2, 7, 27, 113, 483, 2138, 9681, 44374, 205...      27  train
10  19  [1, 3, 8, 38, 71, 73, 108, 166, 288, 376, 656,...      45   test
8   20                             [4, 6, 8, 9, 26, 1752]       6  train
9   21  [1, 2, 1, 3, 4, 2, 4, 8, 8, 3, 5, 13, 19, 15, ...      62  train
11  22  [1, 4, 10, 23, 53, 123, 286, 665, 1546, 3594, ...      28   test
10  23  [1, 176, 570496, 9223556096, 460993706622976, ...       9  train
11  24  [18, 24, 30, 36, 42, 54, 60, 66, 84, 108, 126,...      79  train
12  25  [1, 2, 3, 4, 5, 12, 6, 10, 8, 14, 15, 7, 18, 9...      70   test
12  26  [0, 0, 4, 7, 8, 4, 6, 8, 8, 9, 9, 5, 2, 1, 5, ...      99  train
13  27  [1, -4, 167, -39, 3563, -221, 148649, -37219, ...      19   test
13  28  [648391, 718064159, 7069067389, 22742734291, 3...      16  train
14  29  [9, 24, 41, 60, 81, 103, 125, 148, 172, 196, 2...      42   test
15  30  [1, 2, 1, 2, 2, 2, 3, 2, 4, 3, 2, 3, 4, 6, 5, ...      77   test
16  31  [5, 7, 11, 13, 17, 19, 21, 23, 27, 29, 31, 33,...      54   test
17  32  [1, -34, 510, -4420, 24310, -87516, 204204, -2...      27   test
18  33  [1, 2, -1, 4, -4, 8, 1, -12, 16, 6, -32, 32, -...      41   test
14  34  [1, 1, 3, 1, 3, 7, 1, 3, 11, 19, 1, 3, 15, 35,...      62  train
15  35  [0, 1, 4, 7, 15, 18, 31, 40, 50, 61, 88, 87, 1...      34  train
16  36  [1, 2, 3, 4, 5, 7, 9, 12, 21, 114, 200, 351, 4...      25  train
19  37  [4, 10, 14, 24, 22, 26, 36, 34, 50, 52, 46, 60...      62   test
20  38  [715, 7594479, 84091222866, 931104734002155, 1...       8   test
21  39                               [123, 1234, 1234567]       3   test
17  40                [1, 3, 635, 2049219, 7372235460687]       5  train
18  41  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 24, 36,...      56  train
22  42  [1, 8, 106, 702, 3390, 11496, 33792, 83877, 19...      26   test
23  43  [7, 71, 173, 3719, 91733, 3371947, 749173303, ...      14   test
19  44  [0, 1, 4, 2, 4, 4, 11, 3, 11, 4, 11, 4, 8, 11,...      70  train
24  45  [1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, ...     104   test
20  46  [1, 2, 0, -5, -5, 8, 21, 0, -55, -55, 89, 233,...      40  train
25  47  [12907, 18270, 21569, 32666, 37606, 52126, 543...      30   test
26  48  [0, 1, 3, 4, 9, 12, 13, 28, 37, 40, 41, 90, 11...      43   test
21  49  [1, 0, 0, 56, 15, 56, -1568, -840, -3248, 8696...      27  train
27  50    [1, 7, 18, 139, 2263, 33868, 1366867, 93953872]       8   test

In [8]:
def df_2_dict(df, key_name, value_name):
    return dict(zip(list(df[key_name]), list(df[value_name])))

In [9]:
def plot_sequence(id, save=False):
    value = list(df[df['Id']==id]['Sequence'])[0]
    if save:
        plt.ioff()
    fig = plt.figure()
    plt.plot(np.arange(len(value)), np.asarray(value))
    if not save:
        plt.show()
    else:
        path = os.path.join('/data/zhe.gao/kaggle/integer_sequence_learning', 'plots')
        if not os.path.exists(path):
            os.makedirs(path)
        if not os.path.exists(os.path.join(path, str(id)+'.png')):
            plt.savefig(os.path.join(path, str(id)+'.png'))
    plt.close(fig)

In [21]:
ban_id_list = list(df[df['Sequence'].apply(len)==1]['Id'])

In [22]:
ban_id_list

[1787,
 5524,
 9106,
 13411,
 20895,
 23716,
 28149,
 31920,
 35742,
 42524,
 47237,
 47959,
 54489,
 57149,
 59483,
 60990,
 61946,
 63705,
 63787,
 63809,
 65493,
 66873,
 74774,
 75993,
 77274,
 88628,
 94940,
 106027,
 111077,
 113066,
 116631,
 116901,
 126627,
 132975,
 136766,
 140806,
 152158,
 152441,
 155331,
 159458,
 159928,
 161754,
 165291,
 167547,
 174455,
 175611,
 182454,
 184240,
 185098,
 192432,
 198582,
 203392,
 208239,
 208849,
 209823,
 210822,
 215093,
 215939,
 219150,
 222050,
 222512,
 223343]